#!/bin/bash

xvfb-run --server-args="+extension RANDR" /usr/bin/google-chrome --no-sandbox \
                                --user-data-dir=/data \
                                --no-first-run \
                                --no-default-browser-check \
                                --use-fake-ui-for-media-stream \
                                --use-fake-device-for-media-stream \
                                $@
